pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }
    
    environment {
        SNAP_REPO = 'vprofile-snapshot'
		NEXUS_USER = 'admin'
		NEXUS_PASS = 'admin123'
		RELEASE_REPO = 'vprofile-release'
		CENTRAL_REPO = 'vpro-maven-central'
		NEXUSIP = '13.218.63.191'
		NEXUSPORT = '8081'
		NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'
        SONARSERVER = 'sonarserver'
        SONARSCANNER = 'sonarscanner'
        registryCredntial = 'ecr:us-east-1:awscreds'
        appRegistry = '784607971221.dkr.ecr.us-east-1.amazonaws.com/vprofileappimg'
        vprofileRegistry = 'https://784607971221.dkr.ecr.us-east-1.amazonaws.com'
    }

    stages {
        stage('Build'){
            steps {
                sh 'mvn -s settings.xml -DskipTests install'
            }
            post {
                success {
                    echo "Now Archiving"
                    archiveArtifacts artifacts: '**/*.war'                
                    }
            }
        }
        stage("Build App Image") {
            steps {
                script {
                    dockerImage = docker.build( appRegister + ":BUILD_NUMBER", "./Docker-files/app/multistage/")
                }
            }
        }
        stage ( "Upload App Image") {
            steps{
                script {
                    docker.withRegistryvrofile( vprofileRegistry, registryCredntial) {
                        dockerImage.push("BUILD_NUMBER")
                        dockerImage.push('latest') 
                    }
                }
            }
        }
    }
}